
=>An error occurred on 30/07/2017 at 16:27:26. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.ObjectDisposedException:

Message:

   Cannot access a disposed object.
Object name: 'PhysicsEngine'.

Source: System.Windows.Forms

Stack Trace:

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 78
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 30/07/2017 at 16:31:01. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.ObjectDisposedException:

Message:

   Cannot access a disposed object.
Object name: 'PhysicsEngine'.

Source: System.Windows.Forms

Stack Trace:

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 76
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 30/07/2017 at 16:31:10. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.ObjectDisposedException:

Message:

   Cannot access a disposed object.
Object name: 'PhysicsEngine'.

Source: System.Windows.Forms

Stack Trace:

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 76
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 30/07/2017 at 16:58:51. 

Exception details:

   An error happened while calling the update callback when finished.

Exception number 0:

Exception stack level 0

Type: SlimDX.Direct3D9.Direct3D9Exception:

Message:

   D3DERR_INVALIDCALL: Invalid call (-2005530516)

Source: SlimDX

Stack Trace:

   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Direct3D9.Device.Reset(PresentParameters[] presentParameters)
   at PhysicsEngine.PhysicsEngine.OnClientSizeChanged(EventArgs e) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 126
   at System.Windows.Forms.StyledForm.RefreshBorder() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.UI\System\Windows.Forms\StyledForm.cs:line 3377
   at System.Windows.Forms.StyledForm.OnBorderSizeChangedInner(Int32 widthDiff, Int32 titleBarDiff) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.UI\System\Windows.Forms\StyledForm.cs:line 3040
   at System.Windows.Forms.StyledForm.TitleBarChanged(Int32 widthDiff, Int32 titleBarDiff) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.UI\System\Windows.Forms\StyledForm.cs:line 3025
   at System.Windows.Forms.StyledForm.OnBoundsUpdate(AnimationInfo state) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.UI\System\Windows.Forms\StyledForm.cs:line 2781
   at System.Windows.Forms.AnimationInfo.UpdateInner(Object instance) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.UI\System\Windows.Forms\AnimationState.cs:line 308

=>An error occurred on 31/08/2017 at 21:30:51. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.NullReferenceException:

Message:

   Object reference not set to an instance of an object.

Source: DirectXPhysics

Stack Trace:

   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 228
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 250
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:51. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:51. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:51. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:52. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.NullReferenceException:

Message:

   Object reference not set to an instance of an object.

Source: DirectXPhysics

Stack Trace:

   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 210
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 250
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:52. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:52. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:52. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:52. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:52. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:53. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:54. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:55. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:55. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:56. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:58. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:58. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:58. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.IndexOutOfRangeException:

Message:

   Index was outside the bounds of the array.

Source: mscorlib

Stack Trace:

   at System.Collections.Generic.List`1.Add(T item)
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 193
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:59. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.InvalidOperationException:

Message:

   Collection was modified; enumeration operation may not execute.

Source: mscorlib

Stack Trace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PhysicsEngine.WorldState.<>c__DisplayClass7_0.<ProcessAllContacts>b__1(Int32 i) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Exception stack level 1

Type: System.AggregateException:

Message:

   One or more errors occurred.

Source: mscorlib

Stack Trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at System.Threading.Tasks.ParallelLoop.For(Int32 start, Int32 endExclusive, Action`1 func, Int32 parallellizationCutoff, Int32 maxThreads) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\Tasks\ParallelLoop.cs:line 128
   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 208
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 252
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119

=>An error occurred on 31/08/2017 at 21:30:59. 

Exception details:

   An error happened while invoking a timer callback.

Exception number 0:

Exception stack level 0

Type: System.NullReferenceException:

Message:

   Object reference not set to an instance of an object.

Source: DirectXPhysics

Stack Trace:

   at PhysicsEngine.WorldState.ProcessAllContacts(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 228
   at PhysicsEngine.WorldState.Update(Single dt) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine\WorldState.cs:line 250
   at PhysicsEngine.PhysicsEngine.Timer_Elapsed(Object sender) in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Development\Obsolete\DirectXPhysics\PhysicsEngine.cs:line 75
   at System.Threading.AsyncTimer.RunTimerLoop() in C:\Users\mathu\Desktop\Personal Programs\C# Programs\Ablaze.Net\Ablaze.Suite\System\Threading\AsyncTimer.cs:line 119
